[2025-03-06T17:40:55.185+0000] {processor.py:186} INFO - Started process (PID=48) to work on /opt/airflow/dags/first_dag.py
[2025-03-06T17:40:55.187+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-06T17:40:55.192+0000] {logging_mixin.py:190} INFO - [2025-03-06T17:40:55.192+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-06T17:40:55.215+0000] {logging_mixin.py:190} INFO - [2025-03-06T17:40:55.208+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-06T17:40:55.216+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-06T17:40:55.246+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.077 seconds
[2025-03-06T18:40:20.080+0000] {processor.py:186} INFO - Started process (PID=46) to work on /opt/airflow/dags/first_dag.py
[2025-03-06T18:40:20.082+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-06T18:40:20.087+0000] {logging_mixin.py:190} INFO - [2025-03-06T18:40:20.087+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-06T18:40:20.111+0000] {logging_mixin.py:190} INFO - [2025-03-06T18:40:20.102+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-06T18:40:20.114+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-06T18:40:20.143+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.071 seconds
[2025-03-06T18:40:50.713+0000] {processor.py:186} INFO - Started process (PID=54) to work on /opt/airflow/dags/first_dag.py
[2025-03-06T18:40:50.714+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-06T18:40:50.718+0000] {logging_mixin.py:190} INFO - [2025-03-06T18:40:50.718+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-06T18:40:50.734+0000] {logging_mixin.py:190} INFO - [2025-03-06T18:40:50.731+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-06T18:40:50.735+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-06T18:40:50.765+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.059 seconds
[2025-03-06T18:41:21.259+0000] {processor.py:186} INFO - Started process (PID=63) to work on /opt/airflow/dags/first_dag.py
[2025-03-06T18:41:21.264+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-06T18:41:21.267+0000] {logging_mixin.py:190} INFO - [2025-03-06T18:41:21.266+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-06T18:41:21.284+0000] {logging_mixin.py:190} INFO - [2025-03-06T18:41:21.282+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-06T18:41:21.285+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-06T18:41:21.310+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.058 seconds
[2025-03-06T18:41:51.677+0000] {processor.py:186} INFO - Started process (PID=72) to work on /opt/airflow/dags/first_dag.py
[2025-03-06T18:41:51.679+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-06T18:41:51.680+0000] {logging_mixin.py:190} INFO - [2025-03-06T18:41:51.680+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-06T18:41:51.696+0000] {logging_mixin.py:190} INFO - [2025-03-06T18:41:51.694+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-06T18:41:51.696+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-06T18:41:51.721+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.051 seconds
[2025-03-06T18:42:22.088+0000] {processor.py:186} INFO - Started process (PID=81) to work on /opt/airflow/dags/first_dag.py
[2025-03-06T18:42:22.090+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-06T18:42:22.092+0000] {logging_mixin.py:190} INFO - [2025-03-06T18:42:22.091+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-06T18:42:22.110+0000] {logging_mixin.py:190} INFO - [2025-03-06T18:42:22.105+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-06T18:42:22.112+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-06T18:42:22.136+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.056 seconds
[2025-03-06T18:42:52.499+0000] {processor.py:186} INFO - Started process (PID=90) to work on /opt/airflow/dags/first_dag.py
[2025-03-06T18:42:52.502+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-06T18:42:52.504+0000] {logging_mixin.py:190} INFO - [2025-03-06T18:42:52.504+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-06T18:42:52.521+0000] {logging_mixin.py:190} INFO - [2025-03-06T18:42:52.519+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-06T18:42:52.522+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-06T18:42:52.552+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.063 seconds
[2025-03-06T18:43:22.885+0000] {processor.py:186} INFO - Started process (PID=99) to work on /opt/airflow/dags/first_dag.py
[2025-03-06T18:43:22.887+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-06T18:43:22.888+0000] {logging_mixin.py:190} INFO - [2025-03-06T18:43:22.887+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-06T18:43:22.900+0000] {logging_mixin.py:190} INFO - [2025-03-06T18:43:22.897+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-06T18:43:22.901+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-06T18:43:22.914+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.046 seconds
[2025-03-06T18:43:53.672+0000] {processor.py:186} INFO - Started process (PID=108) to work on /opt/airflow/dags/first_dag.py
[2025-03-06T18:43:53.674+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-06T18:43:53.678+0000] {logging_mixin.py:190} INFO - [2025-03-06T18:43:53.678+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-06T18:43:53.945+0000] {logging_mixin.py:190} INFO - [2025-03-06T18:43:53.941+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-06T18:43:53.945+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-06T18:43:53.968+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.306 seconds
[2025-03-06T18:44:24.611+0000] {processor.py:186} INFO - Started process (PID=123) to work on /opt/airflow/dags/first_dag.py
[2025-03-06T18:44:24.613+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-06T18:44:24.617+0000] {logging_mixin.py:190} INFO - [2025-03-06T18:44:24.616+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-06T18:44:24.640+0000] {logging_mixin.py:190} INFO - [2025-03-06T18:44:24.635+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-06T18:44:24.641+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-06T18:44:24.671+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.073 seconds
[2025-03-06T18:44:55.085+0000] {processor.py:186} INFO - Started process (PID=132) to work on /opt/airflow/dags/first_dag.py
[2025-03-06T18:44:55.087+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-06T18:44:55.089+0000] {logging_mixin.py:190} INFO - [2025-03-06T18:44:55.089+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-06T18:44:55.103+0000] {logging_mixin.py:190} INFO - [2025-03-06T18:44:55.101+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-06T18:44:55.104+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-06T18:44:55.133+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.052 seconds
[2025-03-06T18:45:25.537+0000] {processor.py:186} INFO - Started process (PID=141) to work on /opt/airflow/dags/first_dag.py
[2025-03-06T18:45:25.539+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-06T18:45:25.540+0000] {logging_mixin.py:190} INFO - [2025-03-06T18:45:25.540+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-06T18:45:25.551+0000] {logging_mixin.py:190} INFO - [2025-03-06T18:45:25.549+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-06T18:45:25.551+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-06T18:45:25.574+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.041 seconds
[2025-03-06T18:45:56.091+0000] {processor.py:186} INFO - Started process (PID=150) to work on /opt/airflow/dags/first_dag.py
[2025-03-06T18:45:56.093+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-06T18:45:56.095+0000] {logging_mixin.py:190} INFO - [2025-03-06T18:45:56.095+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-06T18:45:56.109+0000] {logging_mixin.py:190} INFO - [2025-03-06T18:45:56.108+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-06T18:45:56.110+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-06T18:45:56.133+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.051 seconds
[2025-03-06T18:46:26.537+0000] {processor.py:186} INFO - Started process (PID=159) to work on /opt/airflow/dags/first_dag.py
[2025-03-06T18:46:26.538+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-06T18:46:26.540+0000] {logging_mixin.py:190} INFO - [2025-03-06T18:46:26.539+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-06T18:46:26.557+0000] {logging_mixin.py:190} INFO - [2025-03-06T18:46:26.554+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-06T18:46:26.558+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-06T18:46:26.579+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.052 seconds
[2025-03-06T18:46:57.045+0000] {processor.py:186} INFO - Started process (PID=168) to work on /opt/airflow/dags/first_dag.py
[2025-03-06T18:46:57.050+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-06T18:46:57.052+0000] {logging_mixin.py:190} INFO - [2025-03-06T18:46:57.052+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-06T18:46:57.074+0000] {logging_mixin.py:190} INFO - [2025-03-06T18:46:57.066+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-06T18:46:57.075+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-06T18:46:57.109+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.075 seconds
[2025-03-06T18:47:27.436+0000] {processor.py:186} INFO - Started process (PID=177) to work on /opt/airflow/dags/first_dag.py
[2025-03-06T18:47:27.437+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-06T18:47:27.439+0000] {logging_mixin.py:190} INFO - [2025-03-06T18:47:27.439+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-06T18:47:27.457+0000] {logging_mixin.py:190} INFO - [2025-03-06T18:47:27.452+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-06T18:47:27.458+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-06T18:47:27.480+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.049 seconds
[2025-03-06T18:47:57.894+0000] {processor.py:186} INFO - Started process (PID=186) to work on /opt/airflow/dags/first_dag.py
[2025-03-06T18:47:57.897+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-06T18:47:57.899+0000] {logging_mixin.py:190} INFO - [2025-03-06T18:47:57.899+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-06T18:47:57.917+0000] {logging_mixin.py:190} INFO - [2025-03-06T18:47:57.913+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-06T18:47:57.920+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-06T18:47:57.941+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.056 seconds
[2025-03-06T18:48:28.388+0000] {processor.py:186} INFO - Started process (PID=195) to work on /opt/airflow/dags/first_dag.py
[2025-03-06T18:48:28.389+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-06T18:48:28.392+0000] {logging_mixin.py:190} INFO - [2025-03-06T18:48:28.392+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-06T18:48:28.410+0000] {logging_mixin.py:190} INFO - [2025-03-06T18:48:28.407+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-06T18:48:28.411+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-06T18:48:28.435+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.052 seconds
[2025-03-06T18:48:58.892+0000] {processor.py:186} INFO - Started process (PID=204) to work on /opt/airflow/dags/first_dag.py
[2025-03-06T18:48:58.895+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-06T18:48:58.898+0000] {logging_mixin.py:190} INFO - [2025-03-06T18:48:58.897+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-06T18:48:58.917+0000] {logging_mixin.py:190} INFO - [2025-03-06T18:48:58.911+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-06T18:48:58.918+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-06T18:48:58.945+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.068 seconds
[2025-03-06T18:49:29.405+0000] {processor.py:186} INFO - Started process (PID=213) to work on /opt/airflow/dags/first_dag.py
[2025-03-06T18:49:29.407+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-06T18:49:29.409+0000] {logging_mixin.py:190} INFO - [2025-03-06T18:49:29.409+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-06T18:49:29.421+0000] {logging_mixin.py:190} INFO - [2025-03-06T18:49:29.418+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-06T18:49:29.422+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-06T18:49:29.450+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.056 seconds
[2025-03-06T18:49:59.841+0000] {processor.py:186} INFO - Started process (PID=222) to work on /opt/airflow/dags/first_dag.py
[2025-03-06T18:49:59.844+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-06T18:49:59.846+0000] {logging_mixin.py:190} INFO - [2025-03-06T18:49:59.845+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-06T18:49:59.857+0000] {logging_mixin.py:190} INFO - [2025-03-06T18:49:59.856+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-06T18:49:59.858+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-06T18:49:59.885+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.050 seconds
[2025-03-06T18:50:30.469+0000] {processor.py:186} INFO - Started process (PID=231) to work on /opt/airflow/dags/first_dag.py
[2025-03-06T18:50:30.470+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-06T18:50:30.473+0000] {logging_mixin.py:190} INFO - [2025-03-06T18:50:30.472+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-06T18:50:30.489+0000] {logging_mixin.py:190} INFO - [2025-03-06T18:50:30.486+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-06T18:50:30.489+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-06T18:50:30.520+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.064 seconds
[2025-03-06T18:51:00.926+0000] {processor.py:186} INFO - Started process (PID=240) to work on /opt/airflow/dags/first_dag.py
[2025-03-06T18:51:00.929+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-06T18:51:00.933+0000] {logging_mixin.py:190} INFO - [2025-03-06T18:51:00.932+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-06T18:51:00.949+0000] {logging_mixin.py:190} INFO - [2025-03-06T18:51:00.945+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-06T18:51:00.950+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-06T18:51:00.975+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.058 seconds
[2025-03-06T18:51:31.392+0000] {processor.py:186} INFO - Started process (PID=249) to work on /opt/airflow/dags/first_dag.py
[2025-03-06T18:51:31.394+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-06T18:51:31.396+0000] {logging_mixin.py:190} INFO - [2025-03-06T18:51:31.395+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-06T18:51:31.413+0000] {logging_mixin.py:190} INFO - [2025-03-06T18:51:31.411+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-06T18:51:31.413+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-06T18:51:31.436+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.054 seconds
[2025-03-06T19:07:26.764+0000] {processor.py:186} INFO - Started process (PID=258) to work on /opt/airflow/dags/first_dag.py
[2025-03-06T19:07:26.766+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-06T19:07:26.767+0000] {logging_mixin.py:190} INFO - [2025-03-06T19:07:26.767+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-06T19:07:26.784+0000] {logging_mixin.py:190} INFO - [2025-03-06T19:07:26.779+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-06T19:07:26.785+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-06T19:07:26.818+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.067 seconds
[2025-03-06T19:23:19.680+0000] {processor.py:186} INFO - Started process (PID=267) to work on /opt/airflow/dags/first_dag.py
[2025-03-06T19:23:19.681+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-06T19:23:19.685+0000] {logging_mixin.py:190} INFO - [2025-03-06T19:23:19.684+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-06T19:23:19.706+0000] {logging_mixin.py:190} INFO - [2025-03-06T19:23:19.701+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-06T19:23:19.706+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-06T19:23:19.723+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.047 seconds
[2025-03-06T19:23:50.110+0000] {processor.py:186} INFO - Started process (PID=276) to work on /opt/airflow/dags/first_dag.py
[2025-03-06T19:23:50.112+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-06T19:23:50.114+0000] {logging_mixin.py:190} INFO - [2025-03-06T19:23:50.113+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-06T19:23:50.133+0000] {logging_mixin.py:190} INFO - [2025-03-06T19:23:50.127+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-06T19:23:50.134+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-06T19:23:50.150+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.051 seconds
[2025-03-06T19:39:45.286+0000] {processor.py:186} INFO - Started process (PID=285) to work on /opt/airflow/dags/first_dag.py
[2025-03-06T19:39:45.287+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-06T19:39:45.288+0000] {logging_mixin.py:190} INFO - [2025-03-06T19:39:45.288+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-06T19:39:45.309+0000] {logging_mixin.py:190} INFO - [2025-03-06T19:39:45.303+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-06T19:39:45.310+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-06T19:39:45.331+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.054 seconds
[2025-03-06T19:55:13.980+0000] {processor.py:186} INFO - Started process (PID=294) to work on /opt/airflow/dags/first_dag.py
[2025-03-06T19:55:13.983+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-06T19:55:13.985+0000] {logging_mixin.py:190} INFO - [2025-03-06T19:55:13.985+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-06T19:55:14.005+0000] {logging_mixin.py:190} INFO - [2025-03-06T19:55:13.998+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-06T19:55:14.006+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-06T19:55:14.024+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.052 seconds
[2025-03-06T20:11:00.407+0000] {processor.py:186} INFO - Started process (PID=303) to work on /opt/airflow/dags/first_dag.py
[2025-03-06T20:11:00.409+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-06T20:11:00.411+0000] {logging_mixin.py:190} INFO - [2025-03-06T20:11:00.411+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-06T20:11:00.430+0000] {logging_mixin.py:190} INFO - [2025-03-06T20:11:00.422+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-06T20:11:00.431+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-06T20:11:00.449+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.053 seconds
[2025-03-06T20:11:30.841+0000] {processor.py:186} INFO - Started process (PID=312) to work on /opt/airflow/dags/first_dag.py
[2025-03-06T20:11:30.844+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-06T20:11:30.847+0000] {logging_mixin.py:190} INFO - [2025-03-06T20:11:30.847+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-06T20:11:30.869+0000] {logging_mixin.py:190} INFO - [2025-03-06T20:11:30.864+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-06T20:11:30.869+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-06T20:11:30.895+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.062 seconds
[2025-03-06T20:27:26.169+0000] {processor.py:186} INFO - Started process (PID=321) to work on /opt/airflow/dags/first_dag.py
[2025-03-06T20:27:26.171+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-06T20:27:26.174+0000] {logging_mixin.py:190} INFO - [2025-03-06T20:27:26.173+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-06T20:27:26.189+0000] {logging_mixin.py:190} INFO - [2025-03-06T20:27:26.183+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-06T20:27:26.191+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-06T20:27:26.212+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.049 seconds
[2025-03-06T20:43:06.891+0000] {processor.py:186} INFO - Started process (PID=330) to work on /opt/airflow/dags/first_dag.py
[2025-03-06T20:43:06.893+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-06T20:43:06.894+0000] {logging_mixin.py:190} INFO - [2025-03-06T20:43:06.893+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-06T20:43:06.904+0000] {logging_mixin.py:190} INFO - [2025-03-06T20:43:06.902+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-06T20:43:06.904+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-06T20:43:06.920+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.034 seconds
[2025-03-06T20:43:37.267+0000] {processor.py:186} INFO - Started process (PID=339) to work on /opt/airflow/dags/first_dag.py
[2025-03-06T20:43:37.269+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-06T20:43:37.270+0000] {logging_mixin.py:190} INFO - [2025-03-06T20:43:37.270+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-06T20:43:37.284+0000] {logging_mixin.py:190} INFO - [2025-03-06T20:43:37.282+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-06T20:43:37.284+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-06T20:43:37.298+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.035 seconds
[2025-03-06T20:52:54.609+0000] {processor.py:186} INFO - Started process (PID=348) to work on /opt/airflow/dags/first_dag.py
[2025-03-06T20:52:54.610+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-06T20:52:54.613+0000] {logging_mixin.py:190} INFO - [2025-03-06T20:52:54.612+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-06T20:52:54.632+0000] {logging_mixin.py:190} INFO - [2025-03-06T20:52:54.628+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-06T20:52:54.633+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-06T20:52:54.658+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.057 seconds
[2025-03-06T21:08:50.011+0000] {processor.py:186} INFO - Started process (PID=357) to work on /opt/airflow/dags/first_dag.py
[2025-03-06T21:08:50.017+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-06T21:08:50.018+0000] {logging_mixin.py:190} INFO - [2025-03-06T21:08:50.018+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-06T21:08:50.033+0000] {logging_mixin.py:190} INFO - [2025-03-06T21:08:50.027+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-06T21:08:50.034+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-06T21:08:50.058+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.053 seconds
[2025-03-06T21:09:20.469+0000] {processor.py:186} INFO - Started process (PID=366) to work on /opt/airflow/dags/first_dag.py
[2025-03-06T21:09:20.471+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-06T21:09:20.475+0000] {logging_mixin.py:190} INFO - [2025-03-06T21:09:20.475+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-06T21:09:20.488+0000] {logging_mixin.py:190} INFO - [2025-03-06T21:09:20.485+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-06T21:09:20.489+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-06T21:09:20.514+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.050 seconds
[2025-03-06T21:25:14.754+0000] {processor.py:186} INFO - Started process (PID=375) to work on /opt/airflow/dags/first_dag.py
[2025-03-06T21:25:14.756+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-06T21:25:14.757+0000] {logging_mixin.py:190} INFO - [2025-03-06T21:25:14.757+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-06T21:25:14.768+0000] {logging_mixin.py:190} INFO - [2025-03-06T21:25:14.766+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-06T21:25:14.769+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-06T21:25:14.791+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.049 seconds
[2025-03-06T21:41:05.456+0000] {processor.py:186} INFO - Started process (PID=384) to work on /opt/airflow/dags/first_dag.py
[2025-03-06T21:41:05.458+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-06T21:41:05.459+0000] {logging_mixin.py:190} INFO - [2025-03-06T21:41:05.458+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-06T21:41:05.476+0000] {logging_mixin.py:190} INFO - [2025-03-06T21:41:05.474+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-06T21:41:05.479+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-06T21:41:05.499+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.052 seconds
[2025-03-06T21:57:00.658+0000] {processor.py:186} INFO - Started process (PID=393) to work on /opt/airflow/dags/first_dag.py
[2025-03-06T21:57:00.660+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-06T21:57:00.661+0000] {logging_mixin.py:190} INFO - [2025-03-06T21:57:00.661+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-06T21:57:00.681+0000] {logging_mixin.py:190} INFO - [2025-03-06T21:57:00.675+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-06T21:57:00.681+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-06T21:57:00.723+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.077 seconds
[2025-03-06T21:57:31.139+0000] {processor.py:186} INFO - Started process (PID=402) to work on /opt/airflow/dags/first_dag.py
[2025-03-06T21:57:31.141+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-06T21:57:31.143+0000] {logging_mixin.py:190} INFO - [2025-03-06T21:57:31.142+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-06T21:57:31.164+0000] {logging_mixin.py:190} INFO - [2025-03-06T21:57:31.162+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-06T21:57:31.164+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-06T21:57:31.192+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.061 seconds
[2025-03-06T22:13:26.360+0000] {processor.py:186} INFO - Started process (PID=411) to work on /opt/airflow/dags/first_dag.py
[2025-03-06T22:13:26.362+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-06T22:13:26.363+0000] {logging_mixin.py:190} INFO - [2025-03-06T22:13:26.363+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-06T22:13:26.378+0000] {logging_mixin.py:190} INFO - [2025-03-06T22:13:26.375+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-06T22:13:26.378+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-06T22:13:26.398+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.049 seconds
[2025-03-06T22:29:22.536+0000] {processor.py:186} INFO - Started process (PID=420) to work on /opt/airflow/dags/first_dag.py
[2025-03-06T22:29:22.538+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-06T22:29:22.540+0000] {logging_mixin.py:190} INFO - [2025-03-06T22:29:22.540+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-06T22:29:22.568+0000] {logging_mixin.py:190} INFO - [2025-03-06T22:29:22.564+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-06T22:29:22.569+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-06T22:29:22.603+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.078 seconds
[2025-03-06T22:29:53.031+0000] {processor.py:186} INFO - Started process (PID=429) to work on /opt/airflow/dags/first_dag.py
[2025-03-06T22:29:53.032+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-06T22:29:53.034+0000] {logging_mixin.py:190} INFO - [2025-03-06T22:29:53.033+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-06T22:29:53.048+0000] {logging_mixin.py:190} INFO - [2025-03-06T22:29:53.046+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-06T22:29:53.048+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-06T22:29:53.069+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.047 seconds
[2025-03-06T22:45:47.558+0000] {processor.py:186} INFO - Started process (PID=438) to work on /opt/airflow/dags/first_dag.py
[2025-03-06T22:45:47.560+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-06T22:45:47.561+0000] {logging_mixin.py:190} INFO - [2025-03-06T22:45:47.561+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-06T22:45:47.576+0000] {logging_mixin.py:190} INFO - [2025-03-06T22:45:47.572+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-06T22:45:47.577+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-06T22:45:47.597+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.043 seconds
[2025-03-06T23:01:23.893+0000] {processor.py:186} INFO - Started process (PID=447) to work on /opt/airflow/dags/first_dag.py
[2025-03-06T23:01:23.895+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-06T23:01:23.897+0000] {logging_mixin.py:190} INFO - [2025-03-06T23:01:23.897+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-06T23:01:23.916+0000] {logging_mixin.py:190} INFO - [2025-03-06T23:01:23.915+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-06T23:01:23.918+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-06T23:01:23.949+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.063 seconds
[2025-03-06T23:01:54.372+0000] {processor.py:186} INFO - Started process (PID=456) to work on /opt/airflow/dags/first_dag.py
[2025-03-06T23:01:54.376+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-06T23:01:54.378+0000] {logging_mixin.py:190} INFO - [2025-03-06T23:01:54.378+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-06T23:01:54.400+0000] {logging_mixin.py:190} INFO - [2025-03-06T23:01:54.398+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-06T23:01:54.401+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-06T23:01:54.435+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.077 seconds
[2025-03-06T23:17:49.540+0000] {processor.py:186} INFO - Started process (PID=465) to work on /opt/airflow/dags/first_dag.py
[2025-03-06T23:17:49.542+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-06T23:17:49.544+0000] {logging_mixin.py:190} INFO - [2025-03-06T23:17:49.544+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-06T23:17:49.561+0000] {logging_mixin.py:190} INFO - [2025-03-06T23:17:49.559+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-06T23:17:49.562+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-06T23:17:49.583+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.049 seconds
[2025-03-06T23:33:45.409+0000] {processor.py:186} INFO - Started process (PID=474) to work on /opt/airflow/dags/first_dag.py
[2025-03-06T23:33:45.411+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-06T23:33:45.412+0000] {logging_mixin.py:190} INFO - [2025-03-06T23:33:45.411+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-06T23:33:45.429+0000] {logging_mixin.py:190} INFO - [2025-03-06T23:33:45.427+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-06T23:33:45.430+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-06T23:33:45.455+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.050 seconds
[2025-03-06T23:49:20.869+0000] {processor.py:186} INFO - Started process (PID=483) to work on /opt/airflow/dags/first_dag.py
[2025-03-06T23:49:20.870+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-06T23:49:20.873+0000] {logging_mixin.py:190} INFO - [2025-03-06T23:49:20.872+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-06T23:49:20.909+0000] {logging_mixin.py:190} INFO - [2025-03-06T23:49:20.900+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-06T23:49:20.910+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-06T23:49:20.938+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.081 seconds
[2025-03-06T23:49:51.377+0000] {processor.py:186} INFO - Started process (PID=492) to work on /opt/airflow/dags/first_dag.py
[2025-03-06T23:49:51.381+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-06T23:49:51.387+0000] {logging_mixin.py:190} INFO - [2025-03-06T23:49:51.386+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-06T23:49:51.407+0000] {logging_mixin.py:190} INFO - [2025-03-06T23:49:51.403+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-06T23:49:51.408+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-06T23:49:51.439+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.072 seconds
