[2025-03-07T00:05:46.755+0000] {processor.py:186} INFO - Started process (PID=501) to work on /opt/airflow/dags/first_dag.py
[2025-03-07T00:05:46.759+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-07T00:05:46.761+0000] {logging_mixin.py:190} INFO - [2025-03-07T00:05:46.761+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-07T00:05:46.780+0000] {logging_mixin.py:190} INFO - [2025-03-07T00:05:46.774+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-07T00:05:46.781+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-07T00:05:46.806+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.058 seconds
[2025-03-07T00:21:43.025+0000] {processor.py:186} INFO - Started process (PID=510) to work on /opt/airflow/dags/first_dag.py
[2025-03-07T00:21:43.026+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-07T00:21:43.028+0000] {logging_mixin.py:190} INFO - [2025-03-07T00:21:43.028+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-07T00:21:43.042+0000] {logging_mixin.py:190} INFO - [2025-03-07T00:21:43.039+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-07T00:21:43.043+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-07T00:21:43.062+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.046 seconds
[2025-03-07T00:31:18.501+0000] {processor.py:186} INFO - Started process (PID=519) to work on /opt/airflow/dags/first_dag.py
[2025-03-07T00:31:18.502+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-07T00:31:18.503+0000] {logging_mixin.py:190} INFO - [2025-03-07T00:31:18.503+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-07T00:31:18.515+0000] {logging_mixin.py:190} INFO - [2025-03-07T00:31:18.513+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-07T00:31:18.516+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-07T00:31:18.531+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.033 seconds
[2025-03-07T00:47:07.880+0000] {processor.py:186} INFO - Started process (PID=528) to work on /opt/airflow/dags/first_dag.py
[2025-03-07T00:47:07.882+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-07T00:47:07.883+0000] {logging_mixin.py:190} INFO - [2025-03-07T00:47:07.882+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-07T00:47:07.900+0000] {logging_mixin.py:190} INFO - [2025-03-07T00:47:07.893+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-07T00:47:07.901+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-07T00:47:07.925+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.053 seconds
[2025-03-07T01:03:57.968+0000] {processor.py:186} INFO - Started process (PID=537) to work on /opt/airflow/dags/first_dag.py
[2025-03-07T01:03:57.970+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-07T01:03:57.971+0000] {logging_mixin.py:190} INFO - [2025-03-07T01:03:57.971+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-07T01:03:57.986+0000] {logging_mixin.py:190} INFO - [2025-03-07T01:03:57.981+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-07T01:03:57.986+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-07T01:03:58.009+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.049 seconds
[2025-03-07T01:04:28.464+0000] {processor.py:186} INFO - Started process (PID=546) to work on /opt/airflow/dags/first_dag.py
[2025-03-07T01:04:28.466+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-07T01:04:28.467+0000] {logging_mixin.py:190} INFO - [2025-03-07T01:04:28.466+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-07T01:04:28.480+0000] {logging_mixin.py:190} INFO - [2025-03-07T01:04:28.479+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-07T01:04:28.481+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-07T01:04:28.503+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.047 seconds
[2025-03-07T01:20:23.590+0000] {processor.py:186} INFO - Started process (PID=555) to work on /opt/airflow/dags/first_dag.py
[2025-03-07T01:20:23.594+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-07T01:20:23.596+0000] {logging_mixin.py:190} INFO - [2025-03-07T01:20:23.596+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-07T01:20:23.612+0000] {logging_mixin.py:190} INFO - [2025-03-07T01:20:23.607+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-07T01:20:23.613+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-07T01:20:23.643+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.061 seconds
[2025-03-07T01:36:19.868+0000] {processor.py:186} INFO - Started process (PID=564) to work on /opt/airflow/dags/first_dag.py
[2025-03-07T01:36:19.869+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-07T01:36:19.870+0000] {logging_mixin.py:190} INFO - [2025-03-07T01:36:19.870+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-07T01:36:19.892+0000] {logging_mixin.py:190} INFO - [2025-03-07T01:36:19.888+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-07T01:36:19.893+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-07T01:36:19.920+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.058 seconds
[2025-03-07T01:52:15.136+0000] {processor.py:186} INFO - Started process (PID=573) to work on /opt/airflow/dags/first_dag.py
[2025-03-07T01:52:15.140+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-07T01:52:15.143+0000] {logging_mixin.py:190} INFO - [2025-03-07T01:52:15.143+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-07T01:52:15.157+0000] {logging_mixin.py:190} INFO - [2025-03-07T01:52:15.155+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-07T01:52:15.158+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-07T01:52:15.191+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.065 seconds
[2025-03-07T01:52:45.657+0000] {processor.py:186} INFO - Started process (PID=582) to work on /opt/airflow/dags/first_dag.py
[2025-03-07T01:52:45.659+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-07T01:52:45.661+0000] {logging_mixin.py:190} INFO - [2025-03-07T01:52:45.660+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-07T01:52:45.680+0000] {logging_mixin.py:190} INFO - [2025-03-07T01:52:45.672+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-07T01:52:45.683+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-07T01:52:45.710+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.058 seconds
[2025-03-07T02:08:40.977+0000] {processor.py:186} INFO - Started process (PID=591) to work on /opt/airflow/dags/first_dag.py
[2025-03-07T02:08:40.980+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-07T02:08:40.982+0000] {logging_mixin.py:190} INFO - [2025-03-07T02:08:40.982+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-07T02:08:41.001+0000] {logging_mixin.py:190} INFO - [2025-03-07T02:08:40.997+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-07T02:08:41.001+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-07T02:08:41.031+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.061 seconds
[2025-03-07T02:24:37.173+0000] {processor.py:186} INFO - Started process (PID=600) to work on /opt/airflow/dags/first_dag.py
[2025-03-07T02:24:37.174+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-07T02:24:37.175+0000] {logging_mixin.py:190} INFO - [2025-03-07T02:24:37.175+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-07T02:24:37.191+0000] {logging_mixin.py:190} INFO - [2025-03-07T02:24:37.185+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-07T02:24:37.193+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-07T02:24:37.218+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.051 seconds
[2025-03-07T02:25:07.598+0000] {processor.py:186} INFO - Started process (PID=609) to work on /opt/airflow/dags/first_dag.py
[2025-03-07T02:25:07.600+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-07T02:25:07.602+0000] {logging_mixin.py:190} INFO - [2025-03-07T02:25:07.601+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-07T02:25:07.620+0000] {logging_mixin.py:190} INFO - [2025-03-07T02:25:07.618+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-07T02:25:07.620+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-07T02:25:07.645+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.057 seconds
[2025-03-07T02:32:26.220+0000] {processor.py:186} INFO - Started process (PID=618) to work on /opt/airflow/dags/first_dag.py
[2025-03-07T02:32:26.221+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-07T02:32:26.222+0000] {logging_mixin.py:190} INFO - [2025-03-07T02:32:26.221+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-07T02:32:26.239+0000] {logging_mixin.py:190} INFO - [2025-03-07T02:32:26.236+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-07T02:32:26.240+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-07T02:32:26.272+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.058 seconds
[2025-03-07T02:48:21.353+0000] {processor.py:186} INFO - Started process (PID=626) to work on /opt/airflow/dags/first_dag.py
[2025-03-07T02:48:21.353+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-07T02:48:21.354+0000] {logging_mixin.py:190} INFO - [2025-03-07T02:48:21.354+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-07T02:48:21.372+0000] {logging_mixin.py:190} INFO - [2025-03-07T02:48:21.368+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-07T02:48:21.373+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-07T02:48:21.396+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.048 seconds
[2025-03-07T02:48:51.901+0000] {processor.py:186} INFO - Started process (PID=635) to work on /opt/airflow/dags/first_dag.py
[2025-03-07T02:48:51.902+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-07T02:48:51.904+0000] {logging_mixin.py:190} INFO - [2025-03-07T02:48:51.903+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-07T02:48:51.930+0000] {logging_mixin.py:190} INFO - [2025-03-07T02:48:51.922+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-07T02:48:51.933+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-07T02:48:51.965+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.080 seconds
[2025-03-07T03:04:47.064+0000] {processor.py:186} INFO - Started process (PID=644) to work on /opt/airflow/dags/first_dag.py
[2025-03-07T03:04:47.068+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-07T03:04:47.070+0000] {logging_mixin.py:190} INFO - [2025-03-07T03:04:47.070+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-07T03:04:47.092+0000] {logging_mixin.py:190} INFO - [2025-03-07T03:04:47.084+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-07T03:04:47.093+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-07T03:04:47.124+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.067 seconds
[2025-03-07T03:20:43.237+0000] {processor.py:186} INFO - Started process (PID=653) to work on /opt/airflow/dags/first_dag.py
[2025-03-07T03:20:43.239+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-07T03:20:43.240+0000] {logging_mixin.py:190} INFO - [2025-03-07T03:20:43.239+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-07T03:20:43.254+0000] {logging_mixin.py:190} INFO - [2025-03-07T03:20:43.250+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-07T03:20:43.256+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-07T03:20:43.282+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.050 seconds
[2025-03-07T03:33:06.424+0000] {processor.py:186} INFO - Started process (PID=662) to work on /opt/airflow/dags/first_dag.py
[2025-03-07T03:33:06.425+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-07T03:33:06.426+0000] {logging_mixin.py:190} INFO - [2025-03-07T03:33:06.426+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-07T03:33:06.445+0000] {logging_mixin.py:190} INFO - [2025-03-07T03:33:06.441+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-07T03:33:06.445+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-07T03:33:06.470+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.054 seconds
[2025-03-07T03:49:00.822+0000] {processor.py:186} INFO - Started process (PID=671) to work on /opt/airflow/dags/first_dag.py
[2025-03-07T03:49:00.823+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-07T03:49:00.824+0000] {logging_mixin.py:190} INFO - [2025-03-07T03:49:00.823+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-07T03:49:00.839+0000] {logging_mixin.py:190} INFO - [2025-03-07T03:49:00.838+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-07T03:49:00.840+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-07T03:49:00.858+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.041 seconds
[2025-03-07T03:49:31.226+0000] {processor.py:186} INFO - Started process (PID=680) to work on /opt/airflow/dags/first_dag.py
[2025-03-07T03:49:31.227+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-07T03:49:31.229+0000] {logging_mixin.py:190} INFO - [2025-03-07T03:49:31.229+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-07T03:49:31.243+0000] {logging_mixin.py:190} INFO - [2025-03-07T03:49:31.241+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-07T03:49:31.243+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-07T03:49:31.273+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.056 seconds
[2025-03-07T04:05:26.476+0000] {processor.py:186} INFO - Started process (PID=689) to work on /opt/airflow/dags/first_dag.py
[2025-03-07T04:05:26.477+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-07T04:05:26.478+0000] {logging_mixin.py:190} INFO - [2025-03-07T04:05:26.478+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-07T04:05:26.501+0000] {logging_mixin.py:190} INFO - [2025-03-07T04:05:26.490+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-07T04:05:26.502+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-07T04:05:26.530+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.063 seconds
[2025-03-07T04:21:22.671+0000] {processor.py:186} INFO - Started process (PID=698) to work on /opt/airflow/dags/first_dag.py
[2025-03-07T04:21:22.673+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-07T04:21:22.673+0000] {logging_mixin.py:190} INFO - [2025-03-07T04:21:22.673+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-07T04:21:22.690+0000] {logging_mixin.py:190} INFO - [2025-03-07T04:21:22.686+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-07T04:21:22.691+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-07T04:21:22.714+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.049 seconds
[2025-03-07T04:34:03.696+0000] {processor.py:186} INFO - Started process (PID=707) to work on /opt/airflow/dags/first_dag.py
[2025-03-07T04:34:03.697+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-07T04:34:03.698+0000] {logging_mixin.py:190} INFO - [2025-03-07T04:34:03.698+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-07T04:34:03.715+0000] {logging_mixin.py:190} INFO - [2025-03-07T04:34:03.708+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-07T04:34:03.715+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-07T04:34:03.739+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.048 seconds
[2025-03-07T04:34:34.187+0000] {processor.py:186} INFO - Started process (PID=716) to work on /opt/airflow/dags/first_dag.py
[2025-03-07T04:34:34.189+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-07T04:34:34.190+0000] {logging_mixin.py:190} INFO - [2025-03-07T04:34:34.190+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-07T04:34:34.213+0000] {logging_mixin.py:190} INFO - [2025-03-07T04:34:34.207+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-07T04:34:34.216+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-07T04:34:34.245+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.065 seconds
[2025-03-07T04:50:16.701+0000] {processor.py:186} INFO - Started process (PID=725) to work on /opt/airflow/dags/first_dag.py
[2025-03-07T04:50:16.702+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-07T04:50:16.704+0000] {logging_mixin.py:190} INFO - [2025-03-07T04:50:16.703+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-07T04:50:16.720+0000] {logging_mixin.py:190} INFO - [2025-03-07T04:50:16.717+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-07T04:50:16.721+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-07T04:50:16.745+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.051 seconds
[2025-03-07T05:06:12.945+0000] {processor.py:186} INFO - Started process (PID=734) to work on /opt/airflow/dags/first_dag.py
[2025-03-07T05:06:12.945+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-07T05:06:12.947+0000] {logging_mixin.py:190} INFO - [2025-03-07T05:06:12.946+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-07T05:06:12.970+0000] {logging_mixin.py:190} INFO - [2025-03-07T05:06:12.965+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-07T05:06:12.973+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-07T05:06:13.001+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.064 seconds
[2025-03-07T05:06:43.312+0000] {processor.py:186} INFO - Started process (PID=743) to work on /opt/airflow/dags/first_dag.py
[2025-03-07T05:06:43.314+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-07T05:06:43.315+0000] {logging_mixin.py:190} INFO - [2025-03-07T05:06:43.315+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-07T05:06:43.330+0000] {logging_mixin.py:190} INFO - [2025-03-07T05:06:43.326+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-07T05:06:43.330+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-07T05:06:43.352+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.047 seconds
[2025-03-07T05:22:38.410+0000] {processor.py:186} INFO - Started process (PID=752) to work on /opt/airflow/dags/first_dag.py
[2025-03-07T05:22:38.412+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-07T05:22:38.412+0000] {logging_mixin.py:190} INFO - [2025-03-07T05:22:38.412+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-07T05:22:38.429+0000] {logging_mixin.py:190} INFO - [2025-03-07T05:22:38.427+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-07T05:22:38.431+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-07T05:22:38.456+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.054 seconds
[2025-03-07T05:35:13.450+0000] {processor.py:186} INFO - Started process (PID=761) to work on /opt/airflow/dags/first_dag.py
[2025-03-07T05:35:13.451+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-07T05:35:13.453+0000] {logging_mixin.py:190} INFO - [2025-03-07T05:35:13.453+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-07T05:35:13.470+0000] {logging_mixin.py:190} INFO - [2025-03-07T05:35:13.464+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-07T05:35:13.471+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-07T05:35:13.497+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.055 seconds
[2025-03-07T05:35:43.890+0000] {processor.py:186} INFO - Started process (PID=770) to work on /opt/airflow/dags/first_dag.py
[2025-03-07T05:35:43.895+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-07T05:35:43.896+0000] {logging_mixin.py:190} INFO - [2025-03-07T05:35:43.896+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-07T05:35:43.914+0000] {logging_mixin.py:190} INFO - [2025-03-07T05:35:43.912+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-07T05:35:43.915+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-07T05:35:43.943+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.062 seconds
[2025-03-07T05:51:39.034+0000] {processor.py:186} INFO - Started process (PID=779) to work on /opt/airflow/dags/first_dag.py
[2025-03-07T05:51:39.035+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-07T05:51:39.036+0000] {logging_mixin.py:190} INFO - [2025-03-07T05:51:39.036+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-07T05:51:39.049+0000] {logging_mixin.py:190} INFO - [2025-03-07T05:51:39.047+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-07T05:51:39.049+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-07T05:51:39.074+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.050 seconds
[2025-03-07T06:07:34.244+0000] {processor.py:186} INFO - Started process (PID=788) to work on /opt/airflow/dags/first_dag.py
[2025-03-07T06:07:34.247+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-07T06:07:34.248+0000] {logging_mixin.py:190} INFO - [2025-03-07T06:07:34.248+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-07T06:07:34.266+0000] {logging_mixin.py:190} INFO - [2025-03-07T06:07:34.258+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-07T06:07:34.267+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-07T06:07:34.286+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.049 seconds
[2025-03-07T06:08:04.827+0000] {processor.py:186} INFO - Started process (PID=797) to work on /opt/airflow/dags/first_dag.py
[2025-03-07T06:08:04.829+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-07T06:08:04.830+0000] {logging_mixin.py:190} INFO - [2025-03-07T06:08:04.830+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-07T06:08:04.851+0000] {logging_mixin.py:190} INFO - [2025-03-07T06:08:04.847+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-07T06:08:04.851+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-07T06:08:04.891+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.074 seconds
[2025-03-07T06:23:38.026+0000] {processor.py:186} INFO - Started process (PID=806) to work on /opt/airflow/dags/first_dag.py
[2025-03-07T06:23:38.028+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-07T06:23:38.031+0000] {logging_mixin.py:190} INFO - [2025-03-07T06:23:38.030+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-07T06:23:38.054+0000] {logging_mixin.py:190} INFO - [2025-03-07T06:23:38.047+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-07T06:23:38.058+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-07T06:23:38.093+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.074 seconds
[2025-03-07T06:36:22.424+0000] {processor.py:186} INFO - Started process (PID=815) to work on /opt/airflow/dags/first_dag.py
[2025-03-07T06:36:22.425+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-07T06:36:22.426+0000] {logging_mixin.py:190} INFO - [2025-03-07T06:36:22.426+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-07T06:36:22.446+0000] {logging_mixin.py:190} INFO - [2025-03-07T06:36:22.440+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-07T06:36:22.448+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-07T06:36:22.469+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.052 seconds
[2025-03-07T06:52:05.323+0000] {processor.py:186} INFO - Started process (PID=824) to work on /opt/airflow/dags/first_dag.py
[2025-03-07T06:52:05.327+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-07T06:52:05.331+0000] {logging_mixin.py:190} INFO - [2025-03-07T06:52:05.330+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-07T06:52:05.352+0000] {logging_mixin.py:190} INFO - [2025-03-07T06:52:05.342+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-07T06:52:05.352+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-07T06:52:05.383+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.065 seconds
[2025-03-07T07:08:01.581+0000] {processor.py:186} INFO - Started process (PID=834) to work on /opt/airflow/dags/first_dag.py
[2025-03-07T07:08:01.583+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-07T07:08:01.585+0000] {logging_mixin.py:190} INFO - [2025-03-07T07:08:01.585+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-07T07:08:01.606+0000] {logging_mixin.py:190} INFO - [2025-03-07T07:08:01.600+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-07T07:08:01.606+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-07T07:08:01.631+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.060 seconds
[2025-03-07T07:08:32.121+0000] {processor.py:186} INFO - Started process (PID=843) to work on /opt/airflow/dags/first_dag.py
[2025-03-07T07:08:32.125+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-07T07:08:32.127+0000] {logging_mixin.py:190} INFO - [2025-03-07T07:08:32.127+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-07T07:08:32.146+0000] {logging_mixin.py:190} INFO - [2025-03-07T07:08:32.142+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-07T07:08:32.147+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-07T07:08:32.178+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.066 seconds
[2025-03-07T07:24:27.355+0000] {processor.py:186} INFO - Started process (PID=852) to work on /opt/airflow/dags/first_dag.py
[2025-03-07T07:24:27.361+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-07T07:24:27.363+0000] {logging_mixin.py:190} INFO - [2025-03-07T07:24:27.363+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-07T07:24:27.383+0000] {logging_mixin.py:190} INFO - [2025-03-07T07:24:27.375+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-07T07:24:27.385+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-07T07:24:27.412+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.069 seconds
[2025-03-07T07:37:21.533+0000] {processor.py:186} INFO - Started process (PID=861) to work on /opt/airflow/dags/first_dag.py
[2025-03-07T07:37:21.536+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-07T07:37:21.538+0000] {logging_mixin.py:190} INFO - [2025-03-07T07:37:21.538+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-07T07:37:21.559+0000] {logging_mixin.py:190} INFO - [2025-03-07T07:37:21.556+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-07T07:37:21.559+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-07T07:37:21.584+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.057 seconds
[2025-03-07T07:53:16.738+0000] {processor.py:186} INFO - Started process (PID=870) to work on /opt/airflow/dags/first_dag.py
[2025-03-07T07:53:16.739+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-07T07:53:16.741+0000] {logging_mixin.py:190} INFO - [2025-03-07T07:53:16.740+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-07T07:53:16.759+0000] {logging_mixin.py:190} INFO - [2025-03-07T07:53:16.754+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-07T07:53:16.759+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-07T07:53:16.783+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.050 seconds
[2025-03-07T07:53:47.160+0000] {processor.py:186} INFO - Started process (PID=879) to work on /opt/airflow/dags/first_dag.py
[2025-03-07T07:53:47.162+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-07T07:53:47.167+0000] {logging_mixin.py:190} INFO - [2025-03-07T07:53:47.166+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-07T07:53:47.197+0000] {logging_mixin.py:190} INFO - [2025-03-07T07:53:47.193+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-07T07:53:47.198+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-07T07:53:47.227+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.077 seconds
[2025-03-07T08:09:22.884+0000] {processor.py:186} INFO - Started process (PID=888) to work on /opt/airflow/dags/first_dag.py
[2025-03-07T08:09:22.887+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-07T08:09:22.892+0000] {logging_mixin.py:190} INFO - [2025-03-07T08:09:22.890+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-07T08:09:22.925+0000] {logging_mixin.py:190} INFO - [2025-03-07T08:09:22.920+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-07T08:09:22.927+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-07T08:09:22.969+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.099 seconds
[2025-03-07T08:25:18.136+0000] {processor.py:186} INFO - Started process (PID=897) to work on /opt/airflow/dags/first_dag.py
[2025-03-07T08:25:18.138+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-07T08:25:18.139+0000] {logging_mixin.py:190} INFO - [2025-03-07T08:25:18.139+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-07T08:25:18.157+0000] {logging_mixin.py:190} INFO - [2025-03-07T08:25:18.154+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-07T08:25:18.157+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-07T08:25:18.185+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.054 seconds
[2025-03-07T08:25:48.619+0000] {processor.py:186} INFO - Started process (PID=906) to work on /opt/airflow/dags/first_dag.py
[2025-03-07T08:25:48.621+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-07T08:25:48.622+0000] {logging_mixin.py:190} INFO - [2025-03-07T08:25:48.621+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-07T08:25:48.639+0000] {logging_mixin.py:190} INFO - [2025-03-07T08:25:48.638+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-07T08:25:48.640+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-07T08:25:48.662+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.050 seconds
[2025-03-07T08:38:34.341+0000] {processor.py:186} INFO - Started process (PID=915) to work on /opt/airflow/dags/first_dag.py
[2025-03-07T08:38:34.343+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-07T08:38:34.345+0000] {logging_mixin.py:190} INFO - [2025-03-07T08:38:34.344+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-07T08:38:34.361+0000] {logging_mixin.py:190} INFO - [2025-03-07T08:38:34.359+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-07T08:38:34.362+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-07T08:38:34.387+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.052 seconds
[2025-03-07T08:54:30.531+0000] {processor.py:186} INFO - Started process (PID=924) to work on /opt/airflow/dags/first_dag.py
[2025-03-07T08:54:30.535+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-07T08:54:30.542+0000] {logging_mixin.py:190} INFO - [2025-03-07T08:54:30.542+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-07T08:54:30.561+0000] {logging_mixin.py:190} INFO - [2025-03-07T08:54:30.558+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-07T08:54:30.563+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-07T08:54:30.584+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.064 seconds
[2025-03-07T09:01:36.566+0000] {processor.py:186} INFO - Started process (PID=933) to work on /opt/airflow/dags/first_dag.py
[2025-03-07T09:01:36.568+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-07T09:01:36.569+0000] {logging_mixin.py:190} INFO - [2025-03-07T09:01:36.568+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-07T09:01:36.581+0000] {logging_mixin.py:190} INFO - [2025-03-07T09:01:36.579+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-07T09:01:36.582+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-07T09:01:36.603+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.052 seconds
[2025-03-07T09:28:28.019+0000] {processor.py:186} INFO - Started process (PID=942) to work on /opt/airflow/dags/first_dag.py
[2025-03-07T09:28:28.022+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-07T09:28:28.024+0000] {logging_mixin.py:190} INFO - [2025-03-07T09:28:28.023+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-07T09:28:28.059+0000] {logging_mixin.py:190} INFO - [2025-03-07T09:28:28.050+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-07T09:28:28.063+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-07T09:28:28.090+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.099 seconds
[2025-03-07T09:39:16.892+0000] {processor.py:186} INFO - Started process (PID=951) to work on /opt/airflow/dags/first_dag.py
[2025-03-07T09:39:16.893+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-07T09:39:16.895+0000] {logging_mixin.py:190} INFO - [2025-03-07T09:39:16.895+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-07T09:39:16.911+0000] {logging_mixin.py:190} INFO - [2025-03-07T09:39:16.906+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-07T09:39:16.912+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-07T09:39:16.930+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.044 seconds
[2025-03-07T09:39:47.294+0000] {processor.py:186} INFO - Started process (PID=960) to work on /opt/airflow/dags/first_dag.py
[2025-03-07T09:39:47.296+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-07T09:39:47.298+0000] {logging_mixin.py:190} INFO - [2025-03-07T09:39:47.298+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-07T09:39:47.311+0000] {logging_mixin.py:190} INFO - [2025-03-07T09:39:47.310+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-07T09:39:47.312+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-07T09:39:47.336+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.055 seconds
[2025-03-07T09:50:21.830+0000] {processor.py:186} INFO - Started process (PID=969) to work on /opt/airflow/dags/first_dag.py
[2025-03-07T09:50:21.832+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-07T09:50:21.833+0000] {logging_mixin.py:190} INFO - [2025-03-07T09:50:21.833+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-07T09:50:21.849+0000] {logging_mixin.py:190} INFO - [2025-03-07T09:50:21.844+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-07T09:50:21.851+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-07T09:50:21.878+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.063 seconds
[2025-03-07T09:50:52.378+0000] {processor.py:186} INFO - Started process (PID=978) to work on /opt/airflow/dags/first_dag.py
[2025-03-07T09:50:52.380+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-07T09:50:52.382+0000] {logging_mixin.py:190} INFO - [2025-03-07T09:50:52.382+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-07T09:50:52.399+0000] {logging_mixin.py:190} INFO - [2025-03-07T09:50:52.397+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-07T09:50:52.399+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-07T09:50:52.426+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.062 seconds
[2025-03-07T09:51:22.802+0000] {processor.py:186} INFO - Started process (PID=987) to work on /opt/airflow/dags/first_dag.py
[2025-03-07T09:51:22.804+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-07T09:51:22.806+0000] {logging_mixin.py:190} INFO - [2025-03-07T09:51:22.806+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-07T09:51:22.827+0000] {logging_mixin.py:190} INFO - [2025-03-07T09:51:22.823+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-07T09:51:22.827+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-07T09:51:22.854+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.063 seconds
[2025-03-07T09:51:53.391+0000] {processor.py:186} INFO - Started process (PID=996) to work on /opt/airflow/dags/first_dag.py
[2025-03-07T09:51:53.393+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-07T09:51:53.396+0000] {logging_mixin.py:190} INFO - [2025-03-07T09:51:53.396+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-07T09:51:53.409+0000] {logging_mixin.py:190} INFO - [2025-03-07T09:51:53.408+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-07T09:51:53.410+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-07T09:51:53.441+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.060 seconds
[2025-03-07T09:52:23.916+0000] {processor.py:186} INFO - Started process (PID=1005) to work on /opt/airflow/dags/first_dag.py
[2025-03-07T09:52:23.921+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-07T09:52:23.922+0000] {logging_mixin.py:190} INFO - [2025-03-07T09:52:23.921+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-07T09:52:23.941+0000] {logging_mixin.py:190} INFO - [2025-03-07T09:52:23.939+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-07T09:52:23.942+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-07T09:52:23.969+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.066 seconds
[2025-03-07T09:52:54.489+0000] {processor.py:186} INFO - Started process (PID=1014) to work on /opt/airflow/dags/first_dag.py
[2025-03-07T09:52:54.491+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-07T09:52:54.493+0000] {logging_mixin.py:190} INFO - [2025-03-07T09:52:54.492+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-07T09:52:54.513+0000] {logging_mixin.py:190} INFO - [2025-03-07T09:52:54.509+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-07T09:52:54.514+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-07T09:52:54.536+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.060 seconds
[2025-03-07T09:53:24.912+0000] {processor.py:186} INFO - Started process (PID=1023) to work on /opt/airflow/dags/first_dag.py
[2025-03-07T09:53:24.913+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-07T09:53:24.915+0000] {logging_mixin.py:190} INFO - [2025-03-07T09:53:24.915+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-07T09:53:24.933+0000] {logging_mixin.py:190} INFO - [2025-03-07T09:53:24.927+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-07T09:53:24.934+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-07T09:53:24.953+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.049 seconds
[2025-03-07T09:53:55.403+0000] {processor.py:186} INFO - Started process (PID=1031) to work on /opt/airflow/dags/first_dag.py
[2025-03-07T09:53:55.405+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-07T09:53:55.407+0000] {logging_mixin.py:190} INFO - [2025-03-07T09:53:55.407+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-07T09:53:55.422+0000] {logging_mixin.py:190} INFO - [2025-03-07T09:53:55.420+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-07T09:53:55.422+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-07T09:53:55.445+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.052 seconds
[2025-03-07T09:54:25.970+0000] {processor.py:186} INFO - Started process (PID=1040) to work on /opt/airflow/dags/first_dag.py
[2025-03-07T09:54:25.972+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-07T09:54:25.974+0000] {logging_mixin.py:190} INFO - [2025-03-07T09:54:25.973+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-07T09:54:26.000+0000] {logging_mixin.py:190} INFO - [2025-03-07T09:54:25.995+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-07T09:54:26.000+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-07T09:54:26.032+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.074 seconds
[2025-03-07T09:54:56.504+0000] {processor.py:186} INFO - Started process (PID=1049) to work on /opt/airflow/dags/first_dag.py
[2025-03-07T09:54:56.507+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-07T09:54:56.510+0000] {logging_mixin.py:190} INFO - [2025-03-07T09:54:56.509+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-07T09:54:56.525+0000] {logging_mixin.py:190} INFO - [2025-03-07T09:54:56.524+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-07T09:54:56.526+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-07T09:54:56.547+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.052 seconds
[2025-03-07T09:55:27.053+0000] {processor.py:186} INFO - Started process (PID=1058) to work on /opt/airflow/dags/first_dag.py
[2025-03-07T09:55:27.056+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-07T09:55:27.057+0000] {logging_mixin.py:190} INFO - [2025-03-07T09:55:27.056+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-07T09:55:27.071+0000] {logging_mixin.py:190} INFO - [2025-03-07T09:55:27.069+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-07T09:55:27.072+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-07T09:55:27.091+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.050 seconds
[2025-03-07T09:55:57.538+0000] {processor.py:186} INFO - Started process (PID=1067) to work on /opt/airflow/dags/first_dag.py
[2025-03-07T09:55:57.541+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-07T09:55:57.544+0000] {logging_mixin.py:190} INFO - [2025-03-07T09:55:57.544+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-07T09:55:57.565+0000] {logging_mixin.py:190} INFO - [2025-03-07T09:55:57.561+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-07T09:55:57.565+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-07T09:55:57.586+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.055 seconds
[2025-03-07T09:56:28.040+0000] {processor.py:186} INFO - Started process (PID=1076) to work on /opt/airflow/dags/first_dag.py
[2025-03-07T09:56:28.043+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-07T09:56:28.045+0000] {logging_mixin.py:190} INFO - [2025-03-07T09:56:28.045+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-07T09:56:28.062+0000] {logging_mixin.py:190} INFO - [2025-03-07T09:56:28.059+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-07T09:56:28.063+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-07T09:56:28.090+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.061 seconds
[2025-03-07T09:56:58.550+0000] {processor.py:186} INFO - Started process (PID=1085) to work on /opt/airflow/dags/first_dag.py
[2025-03-07T09:56:58.560+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-07T09:56:58.565+0000] {logging_mixin.py:190} INFO - [2025-03-07T09:56:58.564+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-07T09:56:58.579+0000] {logging_mixin.py:190} INFO - [2025-03-07T09:56:58.577+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-07T09:56:58.580+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-07T09:56:58.604+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.065 seconds
[2025-03-07T09:57:29.013+0000] {processor.py:186} INFO - Started process (PID=1094) to work on /opt/airflow/dags/first_dag.py
[2025-03-07T09:57:29.016+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-07T09:57:29.019+0000] {logging_mixin.py:190} INFO - [2025-03-07T09:57:29.019+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-07T09:57:29.039+0000] {logging_mixin.py:190} INFO - [2025-03-07T09:57:29.037+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-07T09:57:29.040+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-07T09:57:29.075+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.071 seconds
[2025-03-07T09:57:59.508+0000] {processor.py:186} INFO - Started process (PID=1103) to work on /opt/airflow/dags/first_dag.py
[2025-03-07T09:57:59.510+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-07T09:57:59.513+0000] {logging_mixin.py:190} INFO - [2025-03-07T09:57:59.512+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-07T09:57:59.532+0000] {logging_mixin.py:190} INFO - [2025-03-07T09:57:59.530+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-07T09:57:59.533+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-07T09:57:59.564+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.073 seconds
[2025-03-07T09:58:30.102+0000] {processor.py:186} INFO - Started process (PID=1112) to work on /opt/airflow/dags/first_dag.py
[2025-03-07T09:58:30.107+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-07T09:58:30.109+0000] {logging_mixin.py:190} INFO - [2025-03-07T09:58:30.109+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-07T09:58:30.138+0000] {logging_mixin.py:190} INFO - [2025-03-07T09:58:30.128+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-07T09:58:30.139+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-07T09:58:30.165+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.079 seconds
[2025-03-07T09:59:00.703+0000] {processor.py:186} INFO - Started process (PID=1121) to work on /opt/airflow/dags/first_dag.py
[2025-03-07T09:59:00.707+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-07T09:59:00.710+0000] {logging_mixin.py:190} INFO - [2025-03-07T09:59:00.709+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-07T09:59:00.728+0000] {logging_mixin.py:190} INFO - [2025-03-07T09:59:00.727+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-07T09:59:00.729+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-07T09:59:00.757+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.065 seconds
[2025-03-07T09:59:31.236+0000] {processor.py:186} INFO - Started process (PID=1130) to work on /opt/airflow/dags/first_dag.py
[2025-03-07T09:59:31.239+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-07T09:59:31.241+0000] {logging_mixin.py:190} INFO - [2025-03-07T09:59:31.240+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-07T09:59:31.261+0000] {logging_mixin.py:190} INFO - [2025-03-07T09:59:31.259+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-07T09:59:31.262+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-07T09:59:31.288+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.061 seconds
[2025-03-07T10:00:01.807+0000] {processor.py:186} INFO - Started process (PID=1139) to work on /opt/airflow/dags/first_dag.py
[2025-03-07T10:00:01.809+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-07T10:00:01.812+0000] {logging_mixin.py:190} INFO - [2025-03-07T10:00:01.812+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-07T10:00:01.828+0000] {logging_mixin.py:190} INFO - [2025-03-07T10:00:01.826+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-07T10:00:01.829+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-07T10:00:01.857+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.067 seconds
[2025-03-07T10:00:32.387+0000] {processor.py:186} INFO - Started process (PID=1148) to work on /opt/airflow/dags/first_dag.py
[2025-03-07T10:00:32.389+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-07T10:00:32.393+0000] {logging_mixin.py:190} INFO - [2025-03-07T10:00:32.393+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-07T10:00:32.411+0000] {logging_mixin.py:190} INFO - [2025-03-07T10:00:32.407+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-07T10:00:32.412+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-07T10:00:32.436+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.063 seconds
[2025-03-07T10:01:02.918+0000] {processor.py:186} INFO - Started process (PID=1157) to work on /opt/airflow/dags/first_dag.py
[2025-03-07T10:01:02.921+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-07T10:01:02.923+0000] {logging_mixin.py:190} INFO - [2025-03-07T10:01:02.922+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-07T10:01:02.937+0000] {logging_mixin.py:190} INFO - [2025-03-07T10:01:02.935+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-07T10:01:02.938+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-07T10:01:02.962+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.057 seconds
[2025-03-07T10:01:33.481+0000] {processor.py:186} INFO - Started process (PID=1166) to work on /opt/airflow/dags/first_dag.py
[2025-03-07T10:01:33.483+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-07T10:01:33.487+0000] {logging_mixin.py:190} INFO - [2025-03-07T10:01:33.487+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-07T10:01:33.506+0000] {logging_mixin.py:190} INFO - [2025-03-07T10:01:33.504+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-07T10:01:33.508+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-07T10:01:33.539+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.079 seconds
[2025-03-07T10:02:04.063+0000] {processor.py:186} INFO - Started process (PID=1175) to work on /opt/airflow/dags/first_dag.py
[2025-03-07T10:02:04.065+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-07T10:02:04.066+0000] {logging_mixin.py:190} INFO - [2025-03-07T10:02:04.066+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-07T10:02:04.088+0000] {logging_mixin.py:190} INFO - [2025-03-07T10:02:04.085+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-07T10:02:04.089+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-07T10:02:04.113+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.065 seconds
[2025-03-07T10:02:34.673+0000] {processor.py:186} INFO - Started process (PID=1184) to work on /opt/airflow/dags/first_dag.py
[2025-03-07T10:02:34.676+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-07T10:02:34.679+0000] {logging_mixin.py:190} INFO - [2025-03-07T10:02:34.678+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-07T10:02:34.693+0000] {logging_mixin.py:190} INFO - [2025-03-07T10:02:34.692+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-07T10:02:34.694+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-07T10:02:34.714+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.051 seconds
[2025-03-07T10:03:05.250+0000] {processor.py:186} INFO - Started process (PID=1193) to work on /opt/airflow/dags/first_dag.py
[2025-03-07T10:03:05.252+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-07T10:03:05.254+0000] {logging_mixin.py:190} INFO - [2025-03-07T10:03:05.253+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-07T10:03:05.273+0000] {logging_mixin.py:190} INFO - [2025-03-07T10:03:05.270+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-07T10:03:05.273+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-07T10:03:05.298+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.063 seconds
[2025-03-07T10:03:35.794+0000] {processor.py:186} INFO - Started process (PID=1202) to work on /opt/airflow/dags/first_dag.py
[2025-03-07T10:03:35.796+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-07T10:03:35.800+0000] {logging_mixin.py:190} INFO - [2025-03-07T10:03:35.799+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-07T10:03:35.818+0000] {logging_mixin.py:190} INFO - [2025-03-07T10:03:35.816+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-07T10:03:35.819+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-07T10:03:35.846+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.069 seconds
[2025-03-07T10:04:06.358+0000] {processor.py:186} INFO - Started process (PID=1211) to work on /opt/airflow/dags/first_dag.py
[2025-03-07T10:04:06.363+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-07T10:04:06.365+0000] {logging_mixin.py:190} INFO - [2025-03-07T10:04:06.364+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-07T10:04:06.381+0000] {logging_mixin.py:190} INFO - [2025-03-07T10:04:06.380+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-07T10:04:06.382+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-07T10:04:06.407+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.061 seconds
[2025-03-07T10:04:36.847+0000] {processor.py:186} INFO - Started process (PID=1220) to work on /opt/airflow/dags/first_dag.py
[2025-03-07T10:04:36.848+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-07T10:04:36.850+0000] {logging_mixin.py:190} INFO - [2025-03-07T10:04:36.850+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-07T10:04:36.870+0000] {logging_mixin.py:190} INFO - [2025-03-07T10:04:36.864+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-07T10:04:36.870+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-07T10:04:36.893+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.054 seconds
[2025-03-07T10:05:07.410+0000] {processor.py:186} INFO - Started process (PID=1229) to work on /opt/airflow/dags/first_dag.py
[2025-03-07T10:05:07.412+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-07T10:05:07.413+0000] {logging_mixin.py:190} INFO - [2025-03-07T10:05:07.413+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-07T10:05:07.434+0000] {logging_mixin.py:190} INFO - [2025-03-07T10:05:07.431+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-07T10:05:07.435+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-07T10:05:07.456+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.066 seconds
[2025-03-07T10:05:37.971+0000] {processor.py:186} INFO - Started process (PID=1238) to work on /opt/airflow/dags/first_dag.py
[2025-03-07T10:05:37.972+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-07T10:05:37.975+0000] {logging_mixin.py:190} INFO - [2025-03-07T10:05:37.975+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-07T10:05:37.992+0000] {logging_mixin.py:190} INFO - [2025-03-07T10:05:37.990+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-07T10:05:37.992+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-07T10:05:38.013+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.050 seconds
[2025-03-07T10:06:08.510+0000] {processor.py:186} INFO - Started process (PID=1247) to work on /opt/airflow/dags/first_dag.py
[2025-03-07T10:06:08.512+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-07T10:06:08.514+0000] {logging_mixin.py:190} INFO - [2025-03-07T10:06:08.514+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-07T10:06:08.535+0000] {logging_mixin.py:190} INFO - [2025-03-07T10:06:08.531+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-07T10:06:08.535+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-07T10:06:08.565+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.063 seconds
[2025-03-07T10:06:38.992+0000] {processor.py:186} INFO - Started process (PID=1256) to work on /opt/airflow/dags/first_dag.py
[2025-03-07T10:06:38.993+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-07T10:06:38.994+0000] {logging_mixin.py:190} INFO - [2025-03-07T10:06:38.994+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-07T10:06:39.008+0000] {logging_mixin.py:190} INFO - [2025-03-07T10:06:39.007+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-07T10:06:39.009+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-07T10:06:39.026+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.041 seconds
[2025-03-07T10:07:09.480+0000] {processor.py:186} INFO - Started process (PID=1265) to work on /opt/airflow/dags/first_dag.py
[2025-03-07T10:07:09.481+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-07T10:07:09.483+0000] {logging_mixin.py:190} INFO - [2025-03-07T10:07:09.482+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-07T10:07:09.494+0000] {logging_mixin.py:190} INFO - [2025-03-07T10:07:09.491+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-07T10:07:09.494+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-07T10:07:09.506+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.031 seconds
[2025-03-07T10:07:39.924+0000] {processor.py:186} INFO - Started process (PID=1274) to work on /opt/airflow/dags/first_dag.py
[2025-03-07T10:07:39.926+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-07T10:07:39.928+0000] {logging_mixin.py:190} INFO - [2025-03-07T10:07:39.928+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-07T10:07:39.943+0000] {logging_mixin.py:190} INFO - [2025-03-07T10:07:39.939+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-07T10:07:39.944+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-07T10:07:39.966+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.049 seconds
[2025-03-07T10:12:12.919+0000] {processor.py:186} INFO - Started process (PID=37) to work on /opt/airflow/dags/first_dag.py
[2025-03-07T10:12:12.921+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-03-07T10:12:12.924+0000] {logging_mixin.py:190} INFO - [2025-03-07T10:12:12.923+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-03-07T10:12:12.941+0000] {logging_mixin.py:190} INFO - [2025-03-07T10:12:12.937+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    prinT("HI")
    ^^^^^
NameError: name 'prinT' is not defined. Did you mean: 'print'?
[2025-03-07T10:12:12.942+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-03-07T10:12:12.972+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.060 seconds
